title: Advanced Computer Architecture Projects
description: Documentation for various CompArch II projects.
theme: just-the-docs

url: https://sidkofi.github.io/cafe-projects

#aux_links:
#Template Repository: https://github.com/just-the-docs/just-the-docs-template
